language: php
os: linux
dist: bionic
env:
  global:
    - XDEBUG_MODE=coverage
before_install:
  - sudo apt-get update
php:
  - '8.1.0'
before_script:
  - composer install
script:
  - composer fulltest
after_success:
  - bash <(curl -s https://codecov.io/bash) -f tmp/coverage.xml
