language: php
os: linux
dist: bionic
before_install:
  - sudo apt-get update
php:
  - '8.1'
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
script:
  - composer fulltest
after_success:
  - bash <(curl -s https://codecov.io/bash)
