name: Code quality

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Tests with code coverage
      run: XDEBUG_MODE=coverage composer test:coverage:xml

    - name: Tests quality - infection
      run: XDEBUG_MODE=coverage composer quality:infection

    - name: Code quality - phpcs
      run: composer quality:phpcs

    - name: Code quality - phpstan
      run: composer quality:phpstan

    - name: Code quality - psalm
      run: composer quality:psalm

    - name: Code quality - phan
      run: composer quality:phan

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
